apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://default.svc
    namespace: longhorn-system
  sources:
    - repoURL: https://longhorn.io
      chart: longhorn
      targetRevision: 1.7.0
      ref: chart-ufficiale
    - repoURL: https://github.com/AndreaFabioGrossi/Patata-Bollente.git
      targetRevision: HEAD
      path: longhorn
      helm:
        valueFiles:
          - $chart-ufficiale/values.yaml
          - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
