apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-vault-secret
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-vault-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: secret/data/grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: secret/data/grafana
        property: password
