apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-db-secret 
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: secret/data/postgresql
        property: password
