apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-external-secret
  namespace: database
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend # Il nome del tuo SecretStore/ClusterSecretStore collegato a Vault
    kind: ClusterSecretStore
  target:
    name: postgresql-external-secret # Il Secret Kubernetes finale che verrà creato
    creationPolicy: Owner
  data:
    - secretKey: password # La chiave richiesta da Postgres nel values.yaml
      remoteRef:
        key: secret/data/postgresql # Il percorso del segreto dentro la UI/CLI di Vault
        property: password        # La chiave del campo dentro Vault
