apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 16.4.1
    releaseName: postgresql
    namespace: database
    valuesFile: values.yaml
resources:
  - external-secret.yaml
